services:
  app:
    build: .
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    env_file:
      - .env
    depends_on:
      - redis
    command: ["npm", "start"]

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
